
name: 'northwind'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  northwind:
    +materialized: table
    database: analytics
  +schema: dbt_sbutello  


